---
  - name: Installation du Virtual IP
    hosts: load_balancers_servers
    become: true
    tasks:
      - name: Installation de KeepAlived
        ansible.builtin.apt:
          name: keepalived
          state: present
      
      - name: Modification du fichier de configuration de KeepAlived
        ansible.builtin.copy:
          src: ../res/keepalived.conf
          dest: /etc/keepalived/keepalived.conf

      - name: Restart KeepAlived
        ansible.builtin.systemd:
          state: restarted
          name: keepalived

      - name: Modification de la priorité dans le fichier keepalived 
        ansible.builtin.replace:
          path: /etc/keepalived/keepalived.conf
          regexp: 'priority 101'
          replace: "priority 100"
        when: ansible_hostname != "loadbalancer1"   
...