---
  - name: Installer les serveurs NGINX
    hosts: web_servers
    become: true
    gather_facts: true
    tasks:
      - name: Installation de NGINX
        ansible.builtin.apt:
          name: nginx
          state: present

      - name: Insertion des fichiers
        ansible.builtin.copy:
          src: ../res/index.html
          dest: /var/www/html/index.html

      - name: Modification des fichiers
        ansible.builtin.replace:
          path: /var/www/html/index.html
          regexp: '\[SERV\]'
          replace: "{{ ansible_hostname }}"
...